name: YT-Battle
version: ${battle.version.string}
description: YT-Battle Plugin
authors: [EXSolo, Rene8888]
website: https://github.com/Rene8888/yt-battle

main: at.er.ytbattle.battle.Battle
database: false

commands:
  battle:
    description: Type /battle help for a command overview
  b:
    description: Type /b help for a command overview