name: Battle
version: 1.9.0
description: Battle Plugin
authors: [EXSolo, Rene8888]
website: http://www.exsoloscript.com

main: at.er.ytbattle.battle.Battle
database: false

commands:
  battle:
    description: Type /battle help for a command overview
  b:
    description: Type /battle help for a command overview